title: Cheng Shao
description: Cheng Shao's personal blog

url: https://github.com/shaocheng16
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 10

navigation:
  - title: Home
    url: /index.html
  - title: About Me
    url: /about
  - title: Research
    url: /research
  - title: Contact
    url: /contact
  - title: Gallery
    url: /photo-gallery

social:
  github: name
  twitter: _shao__cheng_
  facebook: name
  email: brimaidesigns@gmail.com

google_analytics: "UA-58263416-1"
